name: 'Test'
on: [push, pull_request]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest]
            fail-fast: false
        steps:
        - uses: actions/setup-go@v2 
          with:
            go-version: '^1.13.1'
        - run: go version
        - name: test
          run: |
            git clone https://github.com/jfrog/jfrog-cli.git
            cd jfrog-cli
            git checkout test-win
            go test -v github.com\jfrog\jfrog-cli --test.artifactory=true --rt.url=https://ecosysjfrog.jfrog.io/artifactory/ --rt.user=eyalb --rt.password=AKCp5cckSN7LGLkQAmkWyMwqPSwesLJvjamxKQtzLfHTg6NJiSzxABdHLeMpiC2crZ2ECR9Za --timeout 0
            dir out -R

